# Generated by Django 4.0.6 on 2022-10-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingSolution', '0002_alter_sendmoney_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmoney',
            name='holder_name',
            field=models.CharField(default=0, max_length=122),
        ),
    ]
