# Generated by Django 4.0.3 on 2022-07-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingSolution', '0003_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmoney',
            name='name',
            field=models.CharField(default=0, max_length=122),
        ),
        migrations.AlterField(
            model_name='sendmoney',
            name='amount',
            field=models.FloatField(max_length=122),
        ),
    ]
