# Generated by Django 4.0.6 on 2022-09-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingSolution', '0004_sendmoney_name_alter_sendmoney_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmoney',
            name='email',
            field=models.CharField(default='', max_length=122),
        ),
    ]
