# Generated by Django 4.0.6 on 2022-09-29 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingSolution', '0005_sendmoney_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='add',
            field=models.CharField(default=datetime.datetime.now, max_length=122),
        ),
        migrations.AlterField(
            model_name='credit',
            name='add',
            field=models.CharField(default=datetime.datetime.now, max_length=122),
        ),
    ]
