# Generated by Django 4.1.1 on 2022-10-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_Admin_Portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=122)),
                ('bank_name', models.CharField(max_length=122)),
                ('mobile_number', models.CharField(max_length=122)),
                ('account_number', models.CharField(max_length=122)),
                ('card_number', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('male', 'Male'), ('female', 'Female')], max_length=122)),
                ('city', models.CharField(choices=[('', 'Select City'), ('mumbai', 'Mumbai'), ('pune', 'Pune'), ('delhi', 'Delhi')], max_length=122)),
                ('balance', models.FloatField(default=0.0)),
                ('birthdate', models.DateField()),
                ('signature', models.ImageField(blank=True, upload_to='Admin_Portal/signatures')),
            ],
        ),
        migrations.RenameModel(
            old_name='UserRegistration',
            new_name='SuperUserRegistration',
        ),
    ]
