# Generated by Django 4.1.1 on 2022-10-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_Admin_Portal', '0002_users_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_account',
            name='cvv',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='users_account',
            name='expired_date',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='users_account',
            name='bank_name',
            field=models.CharField(choices=[('', 'Select Bank'), ('sbi', 'State Bank Of India'), ('kotak', 'Kotak Mahindra'), ('bom', 'Bank Of Maharashtra')], max_length=122),
        ),
    ]
