# Generated by Django 4.0.6 on 2022-10-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_Admin_Portal', '0003_users_account_cvv_users_account_expired_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_account',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='Admin_Portal/users_profiles'),
        ),
        migrations.AlterField(
            model_name='superuserregistration',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='Admin_Portal/profiles'),
        ),
        migrations.AlterField(
            model_name='users_account',
            name='bank_name',
            field=models.CharField(choices=[('', 'Select Bank'), ('State Bank Of India', 'State Bank Of India'), ('Kotak Mahindra', 'Kotak Mahindra'), ('Bank Of Maharashtra', 'Bank Of Maharashtra')], max_length=122),
        ),
    ]
